### ISSUE TITLE
Ability to send requests form .Net to Node

### ISSUE THREAD

**Issue by hrishabhkumar** [ruidfigueiredo/electron-cgi-dotnet#1]
When we can expect this feature to come?

**Comment by ruidfigueiredo** [comment]
Hopefully soon, it's the thing I plan to work on next. My time has been very limited recently (my son was born recently and I'm moving to another country) but as soon as things settle down I'll start work on that.

**Comment by hrishabhkumar** [comment]
Okay congrats :)

**Comment by ruidfigueiredo** [comment]
You can find a preview version of the functionality to send requests from .Net to Node in the duplex branch: 
https://github.com/ruidfigueiredo/electron-cgi-dotnet/tree/duplex

**Comment by ruidfigueiredo** [comment]
It is now possible to send requests from .Net to Node (version 0.0.5).

Here's a blog post that describes the new functionality: https://www.blinkingcaret.com/2019/11/27/electroncgi-a-solution-to-cross-platform-guis-for-net-core/

Also here's a demo project: https://github.com/ruidfigueiredo/electron-cgi-duplex-reddit-demo
