### ISSUE TITLE
A Javascript error occured in the main process

### ISSUE THREAD

**Issue by edoteee** [ruidfigueiredo/electron-cgi-dotnet#13]
Im getting an error `A Javascript error occured in the main process` when I try to run this project using `npm run start`. This occurs when the dotnet core project sends a message back to electron

![screenshot 404](https://user-images.githubusercontent.com/46995428/104718871-9b09a480-5751-11eb-8786-8bb72a32f47e.png)

I am using the following packages and versions:
**electron-cgi**: ^1.0.6
**electron-cgi-dotne**t: 1.0.4-beta

Have I got something wrong in the project?

**Comment by ruidfigueiredo** [comment]
I'll have to update the nuget package to use .net core 3.1. Nothing you did wrong. I'll let you know when it's live you'll just have to install the new version of `electron-cgi-dotnet` to fix that

**Comment by ruidfigueiredo** [comment]
Can you confirn that the console project you created (where you installed the ElectronCgi.DotNet nuget package) is running netcore 3.0 ? If so you need to upgrade it to 3.1: https://devblogs.microsoft.com/dotnet/net-core-3-0-end-of-life/

**Comment by edoteee** [comment]
The console project was running on dotnet core 3.0. Switching over to 3.1 resolved the issue.

Cheers
