### ISSUE TITLE
how to log in eletron-cgi with log4net?

### ISSUE THREAD

**Issue by HailunTan** [ruidfigueiredo/electron-cgi-dotnet#15]
Hi,

I encountered a problem that the log4net contents, which are supposed to log on the socket server, are  sent  to the client whenever a message is received and handled by the server.    What I want is to log the event when the server received a message but I do not expect that log was sent back to the client.  I am not sure how log4net's API is linked to the electron-cgi for providing the log content to e sent back.. Please advise.

**Comment by ruidfigueiredo** [comment]
electron-cgi relies on the .NET's stdout stream for communication, that's where log4net's consoleappender writes to. If you can use a file appender instead for logging it should be fine.

**Comment by HailunTan** [comment]
Thanks for the replies. I managed to get that working.
