### ISSUE TITLE
Does electron CGI support REST API  and MQTT?

### ISSUE THREAD

**Issue by HailunTan** [ruidfigueiredo/electron-cgi-dotnet#16]
HI,

 I wonder if Electron CGI supports REST API request/response and MQTT subscription/publish.

If electron CGI supported the REST API, how should I specify the method type for REST API request (i.e., POST, GET, UPDATE, etc.)? 

 Also, there is a URL as a recipient  for REST API requests,  I attempted to replace the name of the executables of the server in Electron CGI but it did not work.. So how shall I set this up in electron CGI if it did support REST API?

Also, The same  set of questions go for the MQTT subscriptions and publication.

Please advise.

**Comment by ruidfigueiredo** [comment]
Hi @HailunTan 

ElectronCGI handles communication between the two processes (.NET and Node.js) using the stdin and stdout streams. The communication protocol is very simple and is limited to sending a request with a type and getting a response. There's no notion of GET, POST, UPDATE, etc.

You could launch a server from the .NET side of things and use REST that way. If that's your goal I'd suggest looking at Electron.NET

**Comment by HailunTan** [comment]
Thanks. @ruidfigueiredo. I have an existing REST API server running. My manager required me to  deploy an  electron-CGI-based library to communicate with the server. After viewing the codes in electron-CGI, I  thought it might  not  be feasible to do it but I am not 100% sure so I asked in this section. Thanks for your confirmation and i will have a look at Electron.NET.
