### ISSUE TITLE
Encoding Issues

### ISSUE THREAD

**Issue by jofallas** [ruidfigueiredo/electron-cgi-dotnet#2]
I'm trying to receive some different special characters (é,í, ó, ñ ) from my Electron cgi application but when I receive the data I'm getting: �

**Comment by ruidfigueiredo** [comment]
Those characters shouldn't be a problem, can you provide a specific example of something being sent that fails?

**Comment by jofallas** [comment]
For example in the electron cgi application I'm returning 

this.ExecutionConnection.On<dynamic, string>("loadString", (p) =>
      {
        return "ó";
      });
//
But in my Typescript service when I do:
        connection.Send('loadString', '', (value: any) => {
            console.log(value);
        });
I'm getting in the console '∩┐╜'

**Comment by ruidfigueiredo** [comment]
Just tried it using:
node:
`const { ConnectionBuilder } = require('electron-cgi');

const connection = new ConnectionBuilder().connectTo('dotnet', 'run', '--project', '../dotnet-app').build();

connection.send('loadString', '', res => {
	console.log(res);
	connection.close();
});
`

And dotnet:

`using System;
using ElectronCgi.DotNet;

namespace dotnet_app
{
    class Program
    {
        static void Main(string[] args)
        {
            var connection = new ConnectionBuilder().Build();
	        connection.On<dynamic, string>("loadString", p => 
            {
		        return "ó";
	        });
	        connection.Listen();
        }
    }
}
`
I get the right output:
![image](https://user-images.githubusercontent.com/1956584/72903294-e34fdb80-3d24-11ea-9b7d-2245a6c54f78.png)

Are you by any chance changing encodings somewhere? I made an assumption that both apps (node and dotnet) would be using the same encoding (usually utf8). Also, what platform are you using (Windows, Linux or Mac)?

**Comment by jofallas** [comment]
Thanks, I have the same structure (In my case I´m working with angular) but I have the same, I think that I´m using the same encoding but I´m not sure how to check the encoding of my dot net application.

I´m using windows.

Thanks for your help

**Comment by ruidfigueiredo** [comment]
I'll try it on Windows just to be sure that's not the issue. What I'll try also, maybe for the next version is to explicitly set the encoding used in the the messages exchanged between dotnet and node to utf8, or make that a setting you can change.

**Comment by jofallas** [comment]
Hi we solved the problem, in the main of our program we add: 
`Console.OutputEncoding = System.Text.Encoding.UTF8;`

And now it works Thanks!

**Comment by sbowler** [comment]
I wish this was more clearly documented on the examples or something as it would have saved me at least a couple hours trying to figure out why I was failing to parse the json with UTF-8 encoded characters.

**Comment by ruidfigueiredo** [comment]
Hi @sbowler 

Yes, this needs to be documented and maybe even be an explicit option when creating the connections (i.e. specifying which encoding to use).

Can you provide me some more info into how you ended up with a different encoding in Node and .Net ? That would be helpful so I could think of what would be the best way to add the encoding as an option.

**Comment by lucmax94** [comment]
Hey @ruidfigueiredo,

like mentioned in my E-Mail I will provide some details on how you can reproduce this, it`s pretty much the same like the example @jofallas gave you (Not using it like this, but it shows the two different ways to get this encoding bug):

OS: Windows

In node:
```
connection = new ConnectionBuilder()
        // You can also connect directly to the exe file, it does not matter.
        .connectTo('dotnet', 'run', '--project', 'core/Transformer')
        .build();

connection.on("transformUpdate", (newStatus: string) => {
  console.log("newStatus", newStatus);
});

connection.send("loadEventlogHeader", {}).then((result: string) => {
  console.log("result", result);
});
```

In .net:
```
connection.On<HeaderSetting, string>("loadHeader", headerSettings =>
{
   return "Durchführung der Reise";
});

```
.net example two:

```
connection.Send("transformUpdate", "Durchführung der Reise");
```

Setting the output encoding explicitly - like @jofallas mentioned - also works for me.
Thanky you for your effort!

**Comment by ruidfigueiredo** [comment]
Added the the `UsingEncoding(System.Text.Encoding encoding)` method to `ConnectionBuilder`, usage:

`var connection = new ConnectionBuilder().UsingEncoding(System.Text.Encoding.UTF8).Build()` 

Seems like this issue is always because .NET in some regional settings (only in Windows?) does not use UTF8.
