### ISSUE TITLE
Start connection from .NET to Node

### ISSUE THREAD

**Issue by bampakoa** [ruidfigueiredo/electron-cgi-dotnet#5]
Is it possible to initiate a connection to Node.js code from the .NET application first?

**Comment by ruidfigueiredo** [comment]
@bampakoa That functionality is currently not implemented.  However, it would not be too hard to implement.
From .NET you can start the node process by using `System.Diagnostics.Process.Start `(https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=netframework-4.8) and you can access STDIN/STDOUT using `ProcessStartInfo` (https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.redirectstandardinput?view=netframework-4.8)

In node you can access the Node process' streams by using `process.stdin` and `process.stdout`.

The rest of the code can be reused.

**Comment by bampakoa** [comment]
@ruidfigueiredo thanks very much for your response! If I implement it as you suggest, do I need to connect from Node.JS also using :

```
const connection = new ConnectionBuilder()
        .connectTo('dotnet', 'run', '--project', 'DotNetConsoleProjectWithElectronCgiDotNetNugetPackage')
        .build();
```

**Comment by ruidfigueiredo** [comment]
@bampakoa No, you have to implement a method similar to .NET's connection.Listen where you grab hold of Node.js process' stdind and stdout and use them to initialize the connection on Node.js.
Something like this:
```
const connection = new ConnectionBuilder().listen();
```

and in the listen method:

```
//...
return new Connection(process.stdout, process.stdin);
```
