### ISSUE TITLE
How do you log?

### ISSUE THREAD

**Issue by lookapanda** [ruidfigueiredo/electron-cgi-dotnet#6]
If I use `Console.WriteLine` for logs, the electron main process encounters an error because the logs are not JSON.

**Comment by ruidfigueiredo** [comment]
You have two options, either use `Console.Error.WriteLine` and that will show up in the console window if you are running just Node. If you are running electron it doesn't display (I don't know exactly why).

Alternatively, and this is probably the easiest option, create a request handler for a 'log' request type in Javascript, then in .NET just do `connection.Send('log', 'the thing you want to log');`
The handler in javascript can be something like:

```
connection.on('log', logMessage => {
  console.log(`From .NET: ${logMessage}`);
});
```
And you can see that in the dev tool's console if you are running this in Electron.

Let me know if this helps and if not I can elaborate more on how this works

**Comment by lookapanda** [comment]
Thanks, I ended up doing exactly that before I even opened this issue :D Guess I'll keep doing it!
