### ISSUE TITLE
Thread/Task sleep prevents sending?

### ISSUE THREAD

**Issue by lookapanda** [ruidfigueiredo/electron-cgi-dotnet#7]
Hello,

consider this small program:

```cs
using System.Threading;
using ElectronCgi.DotNet;
using Microsoft.Extensions.Logging;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
			var connection = new ConnectionBuilder()
				.WithLogging(minimumLogLevel: LogLevel.Trace)
				.Build();

			connection.Send("1", 1);
			connection.Send("2", 2);
			Thread.Sleep(5000);
			connection.Send("3", 3);

			connection.Listen();
		}
	}
}
```

What I would expect is, that the first two messages are sent immediately upon start of the program and then the third message is being sent after a 5 second delay. 

But what happens is that no message is sent until those 5 seconds passed and then all are sent at once. Am I doing something wrong here?

**Comment by ruidfigueiredo** [comment]
Hi @lookapanda 

You are doing nothing wrong. The thing is, nothing really happens until you call `connection.Listen()`. 

If you were to do that inside a request handler it would work as you'd expect:

```
            connection.OnAsync("requestType", async () => {
                connection.Send("1", 1);
                connection.Send("2", 2);
                await Task.Delay(5000);
                connection.Send("3", 3);
            });
```
(It's probably not a good idea to use Thread.Sleep given that the code relies on Tasks, see: https://stackoverflow.com/questions/20082221/when-to-use-task-delay-when-to-use-thread-sleep)

Alternatively you can do this as well:
```
            var connection = new ConnectionBuilder().Build();

            Task.Run(async () => {
                connection.Send("1", 1);
                connection.Send("2", 2);
                await Task.Delay(5000);
                connection.Send("3", 3);
            });

            connection.Listen();
```

The reason for this is that the connection really isn't ready until you call `.Listen` (maybe this is poorly named). It's in that method that the `stdin` and `stdout` streams start to be used to send and receive information between Node and .NET

**Comment by lookapanda** [comment]
Thank you! In my usecase (not the one I posted above), I now realized that `Task.Wait()` is similar to `await Something()` and thus it never reached `connection.Listen()` :)
